import { Jugador } from './jugador';

export const Jugadores: Jugador[] = [

    {
        id: 1,
        nombre: "Julio Carpio",
        jersey: 21,
        estatura: 1.71,
        peso: 165,
        posicionF: "Segunda Base",
        posicionB: "Cuarto Bat",
        fec_nacimiento: new Date("19/03/1996")

    },
    {
        id: 2,
        nombre: "Edgar Carpio",
        jersey: 6,
        estatura: 1.69,
        peso: 180,
        posicionF: "Primera Base",
        posicionB: "Primer Bat",
        fec_nacimiento: new Date("26/03/1964")

    },
    {
        id: 3,
        nombre: "Luis Severino",
        jersey: 18,
        estatura: 1.80,
        peso: 171,
        posicionF: "Tercera Base",
        posicionB: "Segundo Bat",
        fec_nacimiento: new Date("21/05/1989")

    },
    {
        id: 4,
        nombre: "Javier Baez",
        jersey: 9,
        estatura: 1.86,
        peso: 179,
        posicionF: "Short Stop",
        posicionB: "Tercer Bat",
        fec_nacimiento: new Date("12/09/1989")

    },
    {
        id: 5,
        nombre: "Kyle Schwarber",
        jersey: 12,
        estatura: 1.83,
        peso: 175,
        posicionF: "Left Fielder",
        posicionB: "Sexto Bat",
        fec_nacimiento: new Date("13/10/1990")

    },
    {
        id: 6,
        nombre: "Albert Almora",
        jersey: 5,
        estatura: 1.88,
        peso: 180,
        posicionF: "Center Fielder",
        posicionB: "Séptimo Bat",
        fec_nacimiento: new Date("22/08/1992")

    },
    {
        id: 7,
        nombre: "Jason Heyward",
        jersey: 22,
        estatura: 1.88,
        peso: 180,
        posicionF: "Center Fielder",
        posicionB: "Séptimo Bat",
        fec_nacimiento: new Date("22/08/1992")

    },
    {
        id: 8,
        nombre: "Willson Contreras",
        jersey: 44,
        estatura: 1.81,
        peso: 180,
        posicionF: "Catcher",
        posicionB: "Octavo Bat",
        fec_nacimiento: new Date("09/01/1993")

    },
    {
        id: 9,
        nombre: "Cole Hamels",
        jersey: 20,
        estatura: 1.90,
        peso: 190,
        posicionF: "Lanzador",
        posicionB: "Noveno Bat",
        fec_nacimiento: new Date("15/07/1984")

    }
];